source = ~/.config/hypr/colors.conf

auth {
  fingerprint {
    enabled = true
    ready_message = Scan fingerprint to unlock
    present_message = Scanning...
    retry_delay = 250 # in milliseconds
  }

}

background {
    monitor =
    path = screenshot
    color = $bg
    blur_passes = 2
    blur_size = 7
}

input-field {
    monitor =
    size = 200, 50
    outline_thickness = 3
    dots_size = 0.33
    dots_spacing = 0.15
    dots_color = $primary
    outer_color = $primary
    inner_color = $surface_variant
    font_color = $fg
    check_color = $secondary
    fail_color = $error
    fade_on_empty = true
    placeholder_text = <i>Password...</i>
    hide_input = false
    position = 0, -20
    halign = center
    valign = center
    rounding = 2
}


# DATE
label {
  monitor =
  text = cmd[update:1000] echo "$(date +"%A, %B %d")"
  color = $secondary
  font_size = 22
  font_family = JetBrains Mono NerdFont
  position = 0, 300
  halign = center
  valign = center
}

# TIME
label {
  monitor =
  text = cmd[update:1000] echo "$(date +"%-I:%M")"
  color = $primary
  font_size = 95
  font_family = JetBrainsMono Nerd Font Mono, Extrabold
  position = 0, 200
  halign = center
  valign = center
}
